import { ChineseChar } from './types';

export const CHINESE_CHARACTERS: ChineseChar[] = [
  { char: '的', pinyin: 'de', meaning: 'de (partícula posesiva)', example: { chinese: '我的书', pinyin: 'Wǒ de shū', meaning: 'Mi libro' } },
  { char: '一', pinyin: 'yī', meaning: 'uno', example: { chinese: '一个人', pinyin: 'Yī gè rén', meaning: 'Una persona' } },
  { char: '是', pinyin: 'shì', meaning: 'ser/estar', example: { chinese: '我是学生', pinyin: 'Wǒ shì xuéshēng', meaning: 'Soy estudiante' } },
  { char: '不', pinyin: 'bù', meaning: 'no/negación', example: { chinese: '我不知道', pinyin: 'Wǒ bù zhīdào', meaning: 'No lo sé' } },
  { char: '了', pinyin: 'le', meaning: 'partícula de aspecto', example: { chinese: '我吃了', pinyin: 'Wǒ chī le', meaning: 'Ya comí' } },
  { char: '人', pinyin: 'rén', meaning: 'persona', example: { chinese: '中国人', pinyin: 'Zhōngguó rén', meaning: 'Persona china' } },
  { char: '我', pinyin: 'wǒ', meaning: 'yo', example: { chinese: '我爱你', pinyin: 'Wǒ ài nǐ', meaning: 'Te amo' } },
  { char: '在', pinyin: 'zài', meaning: 'estar en/en', example: { chinese: '我在家', pinyin: 'Wǒ zài jiā', meaning: 'Estoy en casa' } },
  { char: '有', pinyin: 'yǒu', meaning: 'tener/haber', example: { chinese: '我有一个姐姐', pinyin: 'Wǒ yǒu yī gè jiějiě', meaning: 'Tengo una hermana mayor' } },
  { char: '他', pinyin: 'tā', meaning: 'él', example: { chinese: '他是谁？', pinyin: 'Tā shì shéi?', meaning: '¿Quién es él?' } },
  { char: '这', pinyin: 'zhè', meaning: 'este/esta', example: { chinese: '这是什么？', pinyin: 'Zhè shì shénme?', meaning: '¿Qué es esto?' } },
  { char: '中', pinyin: 'zhōng', meaning: 'centro/medio', example: { chinese: '中文', pinyin: 'Zhōngwén', meaning: 'Idioma chino' } },
  { char: '大', pinyin: 'dà', meaning: 'grande', example: { chinese: '大家', pinyin: 'Dàjiā', meaning: 'Todos (gran familia)' } },
  { char: '来', pinyin: 'lái', meaning: 'venir', example: { chinese: '你来吗？', pinyin: 'Nǐ lái ma?', meaning: '¿Vienes?' } },
  { char: '上', pinyin: 'shàng', meaning: 'arriba/subir', example: { chinese: '早上', pinyin: 'Zǎoshang', meaning: 'Por la mañana' } },
  { char: '国', pinyin: 'guó', meaning: 'país', example: { chinese: '国家', pinyin: 'Guójiā', meaning: 'País / Nación' } },
  { char: '个', pinyin: 'gè', meaning: 'clasificador general', example: { chinese: '那个', pinyin: 'Nà gè', meaning: 'Ese' } },
  { char: '到', pinyin: 'dào', meaning: 'llegar', example: { chinese: '我到了', pinyin: 'Wǒ dào le', meaning: 'He llegado' } },
  { char: '说', pinyin: 'shuō', meaning: 'decir/hablar', example: { chinese: '说话', pinyin: 'Shuōhuà', meaning: 'Hablar' } },
  { char: '们', pinyin: 'men', meaning: 'plural (personas)', example: { chinese: '我们', pinyin: 'Wǒmen', meaning: 'Nosotros' } },
  { char: '为', pinyin: 'wèi', meaning: 'para/por', example: { chinese: '为了你', pinyin: 'Wèile nǐ', meaning: 'Por ti' } },
  { char: '子', pinyin: 'zǐ', meaning: 'hijo/sufijo', example: { chinese: '孩子', pinyin: 'Háizi', meaning: 'Niño/Hijo' } },
  { char: '和', pinyin: 'hé', meaning: 'y/con', example: { chinese: '我和你', pinyin: 'Wǒ hé nǐ', meaning: 'Tú y yo' } },
  { char: '你', pinyin: 'nǐ', meaning: 'tú', example: { chinese: '你好', pinyin: 'Nǐ hǎo', meaning: 'Hola' } },
  { char: '地', pinyin: 'de', meaning: 'tierra/lugar', example: { chinese: '地方', pinyin: 'Dìfāng', meaning: 'Lugar' } },
  { char: '出', pinyin: 'chū', meaning: 'salir', example: { chinese: '出去', pinyin: 'Chūqù', meaning: 'Salir (hacia fuera)' } },
  { char: '道', pinyin: 'dào', meaning: 'camino/decir', example: { chinese: '知道', pinyin: 'Zhīdào', meaning: 'Saber' } },
  { char: '也', pinyin: 'yě', meaning: 'también', example: { chinese: '我也是', pinyin: 'Wǒ yě shì', meaning: 'Yo también' } },
  { char: '时', pinyin: 'shí', meaning: 'tiempo', example: { chinese: '时间', pinyin: 'Shíjiān', meaning: 'Tiempo' } },
  { char: '年', pinyin: 'nián', meaning: 'año', example: { chinese: '明年', pinyin: 'Míngnián', meaning: 'El próximo año' } },
  { char: '得', pinyin: 'de', meaning: 'obtener/poder', example: { chinese: '你看得见吗？', pinyin: 'Nǐ kàn de jiàn ma?', meaning: '¿Puedes ver?' } },
  { char: '就', pinyin: 'jiù', meaning: 'entonces/precisamente', example: { chinese: '就是他', pinyin: 'Jiù shì tā', meaning: 'Es precisamente él' } },
  { char: '那', pinyin: 'nà', meaning: 'ese/esa', example: { chinese: '那里', pinyin: 'Nàlǐ', meaning: 'Allí' } },
  { char: '要', pinyin: 'yào', meaning: 'querer/necesitar', example: { chinese: '我要喝水', pinyin: 'Wǒ yào hē shuǐ', meaning: 'Quiero beber agua' } },
  { char: '下', pinyin: 'xià', meaning: 'abajo/bajar', example: { chinese: '下午', pinyin: 'Xiàwǔ', meaning: 'Por la tarde' } },
  { char: '以', pinyin: 'yǐ', meaning: 'con/usar', example: { chinese: '可以', pinyin: 'Kěyǐ', meaning: 'Poder / Ser posible' } },
  { char: '生', pinyin: 'shēng', meaning: 'nacer/vida', example: { chinese: '生日', pinyin: 'Shēngrì', meaning: 'Cumpleaños' } },
  { char: '会', pinyin: 'huì', meaning: 'saber/poder', example: { chinese: '我会中文', pinyin: 'Wǒ huì Zhōngwén', meaning: 'Sé chino' } },
  { char: '自', pinyin: 'zì', meaning: 'yo mismo/desde', example: { chinese: '自己', pinyin: 'Zìjǐ', meaning: 'Uno mismo' } },
  { char: '着', pinyin: 'zhe', meaning: 'partícula durativa', example: { chinese: '看着', pinyin: 'Kànzhe', meaning: 'Mirando' } },
  { char: '去', pinyin: 'qù', meaning: 'ir', example: { chinese: '我去学校', pinyin: 'Wǒ qù xuéxiào', meaning: 'Voy a la escuela' } },
  { char: '之', pinyin: 'zhī', meaning: 'de (formal)', example: { chinese: '百分之百', pinyin: 'Bǎi fēn zhī bǎi', meaning: 'Cien por ciento' } },
  { char: '过', pinyin: 'guò', meaning: 'pasar/experiencia', example: { chinese: '我去过', pinyin: 'Wǒ qù guò', meaning: 'He ido (alguna vez)' } },
  { char: '家', pinyin: 'jiā', meaning: 'casa/familia', example: { chinese: '回家', pinyin: 'Huí jiā', meaning: 'Volver a casa' } },
  { char: '学', pinyin: 'xué', meaning: 'estudiar', example: { chinese: '学校', pinyin: 'Xuéxiào', meaning: 'Escuela' } },
  { char: '对', pinyin: 'duì', meaning: 'correcto/hacia', example: { chinese: '对不起', pinyin: 'Duìbùqǐ', meaning: 'Lo siento' } },
  { char: '可', pinyin: 'kě', meaning: 'poder/aprobar', example: { chinese: '可爱', pinyin: 'Kě\'ài', meaning: 'Lindo / Adorable' } },
  { char: '她', pinyin: 'tā', meaning: 'ella', example: { chinese: '她的书', pinyin: 'Tā de shū', meaning: 'Su libro (de ella)' } },
  { char: '里', pinyin: 'lǐ', meaning: 'dentro/interior', example: { chinese: '这里', pinyin: 'Zhèlǐ', meaning: 'Aquí' } },
  { char: '后', pinyin: 'hòu', meaning: 'después/detrás', example: { chinese: '后面', pinyin: 'Hòumiàn', meaning: 'Detrás' } },
  { char: '小', pinyin: 'xiǎo', meaning: 'pequeño', example: { chinese: '小孩', pinyin: 'Xiǎohái', meaning: 'Niño pequeño' } },
  { char: '么', pinyin: 'me', meaning: 'qué/partícula', example: { chinese: '怎么', pinyin: 'Zěnme', meaning: 'Cómo' } },
  { char: '心', pinyin: 'xīn', meaning: 'corazón', example: { chinese: '开心', pinyin: 'Kāixīn', meaning: 'Feliz' } },
  { char: '多', pinyin: 'duō', meaning: 'mucho/más', example: { chinese: '多少', pinyin: 'Duōshǎo', meaning: 'Cuánto' } },
  { char: '天', pinyin: 'tiān', meaning: 'cielo/día', example: { chinese: '今天', pinyin: 'Jīntiān', meaning: 'Hoy' } },
  { char: '而', pinyin: 'ér', meaning: 'y/pero', example: { chinese: '而且', pinyin: 'Érqiě', meaning: 'Además' } },
  { char: '能', pinyin: 'néng', meaning: 'poder/capacidad', example: { chinese: '可能', pinyin: 'Kěnéng', meaning: 'Posible' } },
  { char: '好', pinyin: 'hǎo', meaning: 'bueno', example: { chinese: '很好', pinyin: 'Hěn hǎo', meaning: 'Muy bien' } },
  { char: '都', pinyin: 'dōu', meaning: 'todo/todos', example: { chinese: '我们都在', pinyin: 'Wǒmen dōu zài', meaning: 'Todos estamos aquí' } },
  { char: '然', pinyin: 'rán', meaning: 'así/natural', example: { chinese: '虽然', pinyin: 'Suīrán', meaning: 'Aunque' } },
  { char: '没', pinyin: 'méi', meaning: 'no tener/no', example: { chinese: '没关系', pinyin: 'Méiguānxì', meaning: 'No importa' } },
  { char: '日', pinyin: 'rì', meaning: 'sol/día', example: { chinese: '生日快乐', pinyin: 'Shēngrì kuàilè', meaning: 'Feliz cumpleaños' } },
  { char: '于', pinyin: 'yú', meaning: 'en/a', example: { chinese: '关于', pinyin: 'Guānyú', meaning: 'Sobre / Acerca de' } },
  { char: '起', pinyin: 'qǐ', meaning: 'levantarse', example: { chinese: '起床', pinyin: 'Qǐchuáng', meaning: 'Levantarse de la cama' } },
  { char: '还', pinyin: 'hái', meaning: 'todavía/aún', example: { chinese: '还有', pinyin: 'Hái yǒu', meaning: 'Además / Y también' } },
  { char: '发', pinyin: 'fā', meaning: 'enviar/emitir', example: { chinese: '发现', pinyin: 'Fāxiàn', meaning: 'Descubrir' } },
  { char: '成', pinyin: 'chéng', meaning: 'convertirse/lograr', example: { chinese: '成功', pinyin: 'Chénggōng', meaning: 'Éxito' } },
  { char: '事', pinyin: 'shì', meaning: 'asunto/cosa', example: { chinese: '故事', pinyin: 'Gùshì', meaning: 'Historia / Cuento' } },
  { char: '只', pinyin: 'zhǐ', meaning: 'solo/solamente', example: { chinese: '只有', pinyin: 'Zhǐyǒu', meaning: 'Solo hay / Solamente' } },
  { char: '作', pinyin: 'zuò', meaning: 'hacer/trabajo', example: { chinese: '工作', pinyin: 'Gōngzuò', meaning: 'Trabajo' } },
  { char: '当', pinyin: 'dāng', meaning: 'cuando/servir como', example: { chinese: '当然', pinyin: 'Dāngrán', meaning: 'Por supuesto' } },
  { char: '想', pinyin: 'xiǎng', meaning: 'pensar/querer', example: { chinese: '我想你', pinyin: 'Wǒ xiǎng nǐ', meaning: 'Te extraño / Pienso en ti' } },
  { char: '看', pinyin: 'kàn', meaning: 'ver/mirar', example: { chinese: '好看', pinyin: 'Hǎokàn', meaning: 'Bonito (bueno de ver)' } },
  { char: '文', pinyin: 'wén', meaning: 'texto/cultura', example: { chinese: '文化', pinyin: 'Wénhuà', meaning: 'Cultura' } },
  { char: '无', pinyin: 'wú', meaning: 'sin/no tener', example: { chinese: '无论', pinyin: 'Wúlùn', meaning: 'No importa qué' } },
  { char: '开', pinyin: 'kāi', meaning: 'abrir', example: { chinese: '开门', pinyin: 'Kāimén', meaning: 'Abrir la puerta' } },
  { char: '手', pinyin: 'shǒu', meaning: 'mano', example: { chinese: '手机', pinyin: 'Shǒujī', meaning: 'Teléfono móvil' } },
  { char: '十', pinyin: 'shí', meaning: 'diez', example: { chinese: '十月', pinyin: 'Shíyuè', meaning: 'Octubre' } },
  { char: '用', pinyin: 'yòng', meaning: 'usar', example: { chinese: '不用', pinyin: 'Bùyòng', meaning: 'No es necesario' } },
  { char: '主', pinyin: 'zhǔ', meaning: 'principal/maestro', example: { chinese: '主要', pinyin: 'Zhǔyào', meaning: 'Principal' } },
  { char: '行', pinyin: 'xíng', meaning: 'caminar/línea', example: { chinese: '自行车', pinyin: 'Zìxíngchē', meaning: 'Bicicleta' } },
  { char: '方', pinyin: 'fāng', meaning: 'dirección/cuadrado', example: { chinese: '方便', pinyin: 'Fāngbiàn', meaning: 'Conveniente' } },
  { char: '又', pinyin: 'yòu', meaning: 'otra vez/además', example: { chinese: '又来了', pinyin: 'Yòu lái le', meaning: 'Vino otra vez' } },
  { char: '如', pinyin: 'rú', meaning: 'como/si', example: { chinese: '如果', pinyin: 'Rúguǒ', meaning: 'Si (condicional)' } },
  { char: '前', pinyin: 'qián', meaning: 'antes/delante', example: { chinese: '以前', pinyin: 'Yǐqián', meaning: 'Antes' } },
  { char: '所', pinyin: 'suǒ', meaning: 'lugar/lo que', example: { chinese: '所以', pinyin: 'Suǒyǐ', meaning: 'Por eso / Entonces' } },
  { char: '本', pinyin: 'běn', meaning: 'raíz/libro', example: { chinese: '书本', pinyin: 'Shūběn', meaning: 'Libros' } },
  { char: '见', pinyin: 'jiàn', meaning: 'ver', example: { chinese: '再见', pinyin: 'Zàijiàn', meaning: 'Adiós' } },
  { char: '经', pinyin: 'jīng', meaning: 'experiencia/pasar por', example: { chinese: '已经', pinyin: 'Yǐjīng', meaning: 'Ya' } },
  { char: '头', pinyin: 'tóu', meaning: 'cabeza', example: { chinese: '头发', pinyin: 'Tóufa', meaning: 'Cabello' } },
  { char: '面', pinyin: 'miàn', meaning: 'cara/superficie', example: { chinese: '面包', pinyin: 'Miànbāo', meaning: 'Pan' } },
  { char: '公', pinyin: 'gōng', meaning: 'público', example: { chinese: '公园', pinyin: 'Gōngyuán', meaning: 'Parque' } },
  { char: '同', pinyin: 'tóng', meaning: 'mismo/junto', example: { chinese: '同学', pinyin: 'Tóngxué', meaning: 'Compañero de clase' } },
  { char: '三', pinyin: 'sān', meaning: 'tres', example: { chinese: '三点', pinyin: 'Sān diǎn', meaning: 'Las tres (hora)' } },
  { char: '已', pinyin: 'yǐ', meaning: 'ya', example: { chinese: '已知', pinyin: 'Yǐzhī', meaning: 'Conocido' } },
  { char: '老', pinyin: 'lǎo', meaning: 'viejo', example: { chinese: '老师', pinyin: 'Lǎoshī', meaning: 'Maestro' } },
  { char: '从', pinyin: 'cóng', meaning: 'desde', example: { chinese: '从前', pinyin: 'Cóngqián', meaning: 'Érase una vez / Antes' } },
  { char: '动', pinyin: 'dòng', meaning: 'mover/movimiento', example: { chinese: '动物', pinyin: 'Dòngwù', meaning: 'Animal' } },
  { char: '两', pinyin: 'liǎng', meaning: 'dos (con clasificador)', example: { chinese: '两个', pinyin: 'Liǎng gè', meaning: 'Dos (unidades)' } }
];